### ISSUE TITLE
Add NT-selectable switched camera

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/FRCVision-pi-gen#100]
- Add a setting to the webdash to add a switched camera feed, and what NT key should be used for that selection
- Implement in default streamer and all examples

Suggested in [this CD thread](https://www.chiefdelphi.com/t/switch-between-two-cameras-using-joystick-button-java/343521?u=peter_johnson).

**Comment by gartaud** [comment]
Great idea :-) I am looking forward to this feature being implemented.

**Comment by FRC2495** [comment]
Is this new feature in WPILib "CameraServer: Add switched camera support #1600" a sign of good things to come?

**Comment by gartaud** [comment]
Nice! When do you expect to release 2019.3.1?
