### ISSUE TITLE
Default Python Package Availability - pynetworktables

### ISSUE THREAD

**Issue by Sn3akyP3t3** [wpilibsuite/FRCVision-pi-gen#127]
Please install pynetworktables as part of the default image.

**Comment by ThadHouse** [comment]
It is included as part of the image. Are you seeing it not work?

**Comment by PeterJohnson** [comment]
Make sure you’re running python3, not python.

**Comment by Sn3akyP3t3** [comment]
Different platform, different command.  Wasn't running pip3 install which let me to believe it wasn't installed.  Not an issue.
