### ISSUE TITLE
import cv2 fails on python3 on 2020.1.1

### ISSUE THREAD

**Issue by kglasnapp** [wpilibsuite/FRCVision-pi-gen#132]
I attempted import cv2  on python3 on 2020.1.1 -- the result was file not found.  

I did an import cv2 with a 2019.3.1 image and it worked. What am I doing wrong?

**Comment by PeterJohnson** [comment]
You're not doing anything wrong, looks like a bug in the 2020 beta image.

**Comment by auscompgeek** [comment]
It looks like the stage3 build does look for Python 3.7 correctly, but the package list includes python3.5 instead of python3.7.

**Comment by joecaraccio** [comment]
Also experiencing this..we were so confused how the image didn't include cv2.

Does anyone know how to generate a release of the image to be flashed? I spend most of my time on a windows machine so didn't want to deal with setting up all that stuff

**Comment by PeterJohnson** [comment]
There's an easy patch fix if you don't want to reflash the whole image, just ssh in, make the filesystem writable with `rw`, and run `sudo ln -sf /usr/local/frc/lib/python3.7/dist-packages/cv2 /usr/local/lib/python3.7/dist-packages/cv2`
