### ISSUE TITLE
Trying to modify the web dashboard

### ISSUE THREAD

**Issue by cl3t0** [wpilibsuite/FRCVision-pi-gen#136]
Is it possible? Where can I find these files? I want to integrate some new code to the dashboard. I created a calibration page in another port and I want to create a hyperlink button to it. Thank you!

**Comment by PeterJohnson** [comment]
Source code is here on GitHub: https://github.com/wpilibsuite/FRCVision-pi-gen/tree/frcvision/deps/tools/configServer

The sources are also located in /usr/src/configServer in the image itself.

**Comment by cl3t0** [comment]
Thanks!
