### ISSUE TITLE
setuidgids: FATAL: unable to run ./runCamera

### ISSUE THREAD

**Issue by Bertonebreno** [wpilibsuite/FRCVision-pi-gen#148]
I think I deleted the file runCamera, and now it's impossible to run the file, even though it's the same as it was before.

**Comment by PeterJohnson** [comment]
Is it executable?  `ls -l runCamera` should look like this:
```
-rwxr-xr-x 1 pi   pi       106 Dec 30 22:00 runCamera
```

If it doesn't, run `chmod a+x runCamera`

**Comment by Bertonebreno** [comment]
Thank you! It was just this dumb mistake
