### ISSUE TITLE
Information to SmartDashboard?

### ISSUE THREAD

**Issue by charlesnguyentheguy** [wpilibsuite/FRCVision-pi-gen#50]
Hello! We are team 2557, and we were wondering if there is a way to access the SmartDashboard on the pi in the frc vision image. It seems that it doesn't contain the jar file for wpilib, which contains the smartdashboard classes. Thanks!

**Comment by PeterJohnson** [comment]
The SmartDashboard class is a pretty thin wrapper around NetworkTables, as you can see from the implementation: https://github.com/wpilibsuite/allwpilib/blob/master/wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java

While you won't be able to just copy the SmartDashboard.java file into your project, you can write to things visible in SmartDashboard fairly easily by using NetworkTables directly.

I'll look to see how hard it is to include wpilibj in the image.

**Comment by charlesnguyentheguy** [comment]
Hello Mr. Johnson,

Thank you so much! We'll definitely try using network tables directly. We'd
really appreciate it if you were able to include wpilibj in the image.

Sincerely,
Programming team of 2557
