### ISSUE TITLE
Getting Error message about Port  1181 "already in use"

### ISSUE THREAD

**Issue by changaimaraSA** [wpilibsuite/FRCVision-pi-gen#77]
Please forgive if this is the wrong place for this question, but we're trying to run some custom python code and we're getting the following error:

`CS: ERROR: bind() to port 1181 failed: Address already in use (TCPAcceptor.cpp:117)`

Is it possible that some other code on the Raspberry Pi image is bound to the port? Maybe the application that comes up on frcvision.local? Can we turn that application off?

**Comment by PeterJohnson** [comment]
Yes, the default application sets up cameras there.  It’s easy to disable/upload your own application via the “Application” tab of the web dashboard.  Just select custom or uploaded python app.  I recommend looking at the example zip files on that page as well.

**Comment by changaimaraSA** [comment]
Ah! Thank you so much!
