### ISSUE TITLE
Improve file upload feedback

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/FRCVision-pi-gen#82]
Currently a successful file upload doesn't provide any visual feedback.  The only thing that changes is the file upload changes to no file selected.  This is not very intuitive for new users.  A clear visual indication that the upload succeeded would be better.

**Comment by Sub6Resources** [comment]
In addition, a dialog stating that the Pi is in read only mode would be helpful while trying to upload a new program.
