### ISSUE TITLE
Line Endings - Need Correction On Import

### ISSUE THREAD

**Issue by Sn3akyP3t3** [wpilibsuite/FRCVision-pi-gen#92]
Code files passed over from client to the Pi via the interface should get their line endings corrected prior o execution.  I suggest running dos2unix against uploads.  Probably should do the same for the json import process if not done already.

**Comment by ThadHouse** [comment]
Are you using the 2019.2.1 update? This was fixed in that update.

**Comment by Sn3akyP3t3** [comment]
I believe so, I downloaded the latest release image the night before opening the ticket.

**Comment by PeterJohnson** [comment]
Which application type are you using?  Line endings are only converted for the "Uploaded Python file" application type.

**Comment by Sn3akyP3t3** [comment]
Test revealed that line endings are LF and not CRLF after the upload.  I can't recreate so it must be something I did that led to a false alarm.  This one can be closed.
