### ISSUE TITLE
Raspberry pi camera support

### ISSUE THREAD

**Issue by liloheinrich** [wpilibsuite/FRCVision-pi-gen#93]
I have a raspberry pi official camera module that I want to use for vision and I was wondering if it is supported by the FRC image, as the description doesn’t explicitly list what types of cameras are supported. I’m having errors, but they could be related to the hardware.

**Comment by PeterJohnson** [comment]
Yes, it’s supported and enabled by default in the 2019.2.1 release (it was not enabled by default in the kickoff 2019.1.1 release).
